### ISSUE TITLE
`npm run dev`で正常に動作しない（必要なパッケージの不足？）

### ISSUE THREAD

**Issue by NONONOexe** [ringo-ringo-ringo/ringo-viewer#18]
`npm run dev`コマンドによる実行が正常にできませんでした。出力されたエラーとログファイルを添付します。

エラーの内容：
```
$ npm run dev

> ringo-viewer@0.1.0 dev
> next dev

(node:19048) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\autumn-camp\ringo-viewer\next.config.js:7
export default nextConfig;
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.18.0
```

ログ：
[rescue.log](https://github.com/user-attachments/files/17967583/rescue.log)

---

警告の出力にしたがい、package.jsonに「"module": "type"」を加えたところ、実行されたのですがhttpアクセス後、ランタイムエラーとなりました。

ランタイムエラーの画面：
<img width="421" alt="エラー画面" src="https://github.com/user-attachments/assets/66a6d0bc-6c1a-401e-b7c9-29c56b5bd688">

編集後のpackage.json：
[package.json](https://github.com/user-attachments/files/17967592/package.json)

わかることがあれば、共有いただけたらと思います。

なにか環境によって必要なパッケージが不足している状況があるのかもしれません。解決のために、追加で必要な情報や操作があれば聞いてください。

**Comment by nono2224** [comment]
node jsで使えれるモジュールシステムとして
- Common JS
  - import()またはexport()を使用してモジュールの使用が可能
- ES Modules
  - require()またはmodule()を使用してモジュールの使用が可能

の2つがあります

上記のエラーは，Common JSとして全てのファイルを読み込もうとしているため，ES Modulesのファイルを読み込むことができず，吐かれたエラーだと推測します
そのエラーの解決方法は，エラー文にも書かれている通り，package.json内に`"type": "module"`と記述すること，もしくはES Modulesファイルの拡張子を`.mjs`と明示的に記述することです

しかし，package.json内に`"type": "module"`と記述すると，全てのファイルをES Modulesとして読み込もうとします．
本システムは，Common JSとES Modulesの2つのモジュールシステムを使用しています
そのため，次はES Modulesとして全てのファイルを読み込もうとしているため，Common JSのファイルを読み込むことができず，ランタイムエラーが吐かれたと推測しています

一方，nodeのバージョンを上げることにより，上記のようなエラーは出ないことがあります
これは，ES Modulesのサポートが強化され、Common JS とES Modulesの相互運用性が向上しているためです
現状動作確認が取れているnodeのバージョンは22以降です

そのため，nodeのバージョンを22以降にしていただけると，動作すると思われます


---


上記内容は，私が独自に調べた内容です
間違いがありましたら，ご指摘お願いします

また，本問題は，本システムの環境指定を行なっていないことによるものであり，動作確認不足の部分もありました
ご指摘ありがとうございます
今後改善させていただきます

**Comment by NONONOexe** [comment]
連絡いただいたとおり、nodeのバージョンを最新化したところ解決しました。
対応いただきありがとうございました。
